Vagrant.configure("2") do |config|
  config.vm.box = "example/ubuntu"
  config.vm.provider "vmware_desktop"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "./lib", "/vagrant/lib"
  config.vm.provision "shell", inline: "echo setup"
end
